---
 - name: Distribute hosts
   hosts: all

   tasks:
    - name: copy local file
      copy:
        src: /etc/hosts
        dest: /etc
    - name: Set Hostname
      hostname:
        name: "{{inventory_hostname}}"
