---
 - name: "My First Playbook"
   hosts: all 
`
   tasks:
   - name: "connectivity test"
     ping:

   - name: Install Apache
      yum:
        name: httpd
        state: present
    
   - name: check running
     service: 
      name: httpd
      state: started
   
       

