---

 - name: COPY HOSTS	

   hosts: all 


   tasks: 
   - name: Copying file
     become: true
     copy: 
       src: /etc/hosts
       dest: /etc
       mode: 0644
   - name: change permissions
     file:
      path:
       /root/ans-red/doublebat
      mode: a+w
      

