---

- name: test webuser add
  hosts: all
  become: true
  vars :
    username:
       uname: drwho
       description: Test Account

    
  tasks:
    - name: create the username
      user: 
        name: "{{username}}"
        comment: Bunch of arse
        state: present
    
